@php
    /** @var \App\Models\PossessionCase $case */
    $b = $booking;
    $primary = $brand['primary'] ?? '#2563eb';
@endphp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { margin: 0; color: #1f2933; font-size: 12px; line-height: 1.6; }
        .wrap { padding: 40px 48px; }
        .head { border-bottom: 3px solid {{ $primary }}; padding-bottom: 12px; margin-bottom: 24px; }
        .company { font-size: 20px; font-weight: bold; color: {{ $primary }}; }
        h1 { font-size: 17px; letter-spacing: 1px; margin: 22px 0 4px; text-transform: uppercase; }
        .num { color: #52606d; font-size: 12px; margin-bottom: 16px; }
        table.kv { width: 100%; border-collapse: collapse; margin: 12px 0; }
        table.kv td { padding: 6px 8px; vertical-align: top; border-bottom: 1px solid #e4e7eb; }
        table.kv td.label { color: #7b8794; width: 34%; }
        .section-title { margin-top: 22px; font-weight: bold; color: {{ $primary }}; text-transform: uppercase; letter-spacing: 1px; font-size: 11px; }
        p.body { margin: 14px 0; }
        .sign-row { margin-top: 64px; }
        .sign-row td { width: 45%; padding-top: 6px; border-top: 1px solid #1f2933; font-size: 11px; }
        .foot { margin-top: 40px; border-top: 1px solid #cbd2d9; padding-top: 10px; color: #7b8794; font-size: 10px; }
    </style>
</head>
<body>
<div class="wrap">
    <div class="head">
        <div class="company">{{ $brand['name'] }}</div>
        <div style="color:#7b8794">{{ $brand['name'] }} Business OS</div>
    </div>

    <h1>Certificate of Possession</h1>
    <div class="num">{{ $case->case_number }} &middot; issued {{ now()->format('d M Y') }}</div>

    <p class="body">
        This is to certify that possession of the plot described below has been handed over to
        the owner(s) named herein by {{ $brand['name'] }} on
        <strong>{{ optional($handoverDate)->format('d M Y') ?? now()->format('d M Y') }}</strong>.
    </p>

    <div class="section-title">Property</div>
    <table class="kv">
        <tr><td class="label">Booking</td><td>{{ $b->booking_number }}</td></tr>
        <tr><td class="label">Project</td><td>{{ $b->project?->name ?? '—' }}</td></tr>
        <tr><td class="label">Plot</td><td>{{ $b->block?->name }} / Plot {{ $b->plot?->plot_number }} &middot; {{ $b->plot?->areaLabel() }}</td></tr>
        <tr><td class="label">Booking date</td><td>{{ $b->booking_date?->format('d M Y') }}</td></tr>
        <tr><td class="label">Possession date</td><td>{{ optional($handoverDate)->format('d M Y') ?? now()->format('d M Y') }}</td></tr>
    </table>

    <div class="section-title">Owner(s)</div>
    <table class="kv">
        @foreach ($owners as $o)
            <tr><td class="label">{{ $o['is_primary'] ? 'Primary owner' : 'Co-owner' }}</td><td>{{ $o['name'] }} ({{ $o['customer_code'] }})</td></tr>
        @endforeach
    </table>

    <table class="kv sign-row">
        <tr>
            <td>Customer acknowledgement<br><span style="color:#7b8794">{{ $case->handover?->received_by ?? '________________' }}</span></td>
            <td style="width:10%"></td>
            <td>For {{ $brand['name'] }}<br><span style="color:#7b8794">{{ $representative }}</span></td>
        </tr>
    </table>

    <div class="foot">
        Generated by {{ $brand['name'] }} Business OS. This certificate references the historical booking
        terms and does not alter any pricing, registry or ownership record.
    </div>
</div>
</body>
</html>
